name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
          php-version: '8.1'
          coverage: none
          tools: composer:v2
          extensions: mbstring, xml, ctype, iconv, intl, dom, filter, gd, iconv, json
      env:
          update: true
          
    - uses: actions/checkout@v4
    - name: Build the Docker image
      run: docker build -t weather-forecast .
